# Generated by Django 3.1.5 on 2021-01-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log_errors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_occured', models.DateTimeField(auto_now_add=True)),
                ('errors', models.TextField(blank=True)),
            ],
        ),
    ]
