"""
Django settings for django_school project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from pathlib import Path
# from decouple import config
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# PROJECT_DIR = BASE_DIR / 'django_school'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v^qhk(gj==5tlr&%e-76b_#3l*rd#!=x72xnyxcfdeq^lk(%9(' # config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # config('DEBUG', cast=bool)


ALLOWED_HOSTS = ['*'] # config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'homepage',
    "account",
    'bootstrapform',
    # 'selectize',
    'paypal.standard.ipn',
    'captcha',
    # custom apps
    
    'payments',    
    'ajaxviews',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "account.middleware.LocaleMiddleware",
    "account.middleware.TimezoneMiddleware",
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'mysite' / 'templates', 
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}





# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

AUTH_USER_MODEL = 'ajaxviews.MyUser'

from django.conf import global_settings
# TEMPLATE_CONTEXT_PROCESSORS = global_settings.TEMPLATE_CONTEXT_PROCESSORS + (
#     "django.core.context_processors.request", "account.context_processors.account",
# )
AUTHENTICATION_BACKENDS = global_settings.AUTHENTICATION_BACKENDS+[
    "account.auth_backends.EmailAuthenticationBackend",
]

# gmail server settings
EMAIL_HOST = 'smtp.webfaction.com'
EMAIL_HOST_USER = 'flexspot'
EMAIL_HOST_PASSWORD = 'Password123'#'pnaoeogqwtqlgusd'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'support@flexspot.co'
SERVER_EMAIL = 'support@www.flexlot.co'
#django-user-accounts
ACCOUNT_EMAIL_UNIQUE = True
ACCOUNT_EMAIL_CONFIRMATION_REQUIRED = True



PAYPAL_RECEIVER_EMAIL = "info@flexspot.co"
PAYPAL_REDIRECT_URL = "http://www.flexspot.co"
PAYPAL_TEST = False



#DJango recaptcha(https://www.google.com/recaptcha/admin)

RECAPTCHA_PUBLIC_KEY = '6LfgU_oSAAAAAABjYNwiprQV-9BO9yH7C9pkGDkt'
RECAPTCHA_PRIVATE_KEY = '6LfgU_oSAAAAAORVMk6HGflbZx0rbShkn2sNjlXY'
RECAPTCHA_USE_SSL = False




# """
# Django settings for mysite project.

# For more information on this file, see
# https://docs.djangoproject.com/en/1.6/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/1.6/ref/settings/
# """

# # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# import os
# BASE_DIR = os.path.dirname(os.path.dirname(__file__))


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/1.6/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'v^qhk(gj==5tlr&%e-76b_#3l*rd#!=x72xnyxcfdeq^lk(%9('

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False

# TEMPLATE_DEBUG = DEBUG

# ALLOWED_HOSTS = [
#     '.flexspot.co',
#     '.flexspot.webfactional.com',
#     '.flexlot.co',
#    # '127.0.0.1', 'localhost'
# ]


# # Application definition

# INSTALLED_APPS = (
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'django.contrib.sites',
#     # apps
#     'homepage',
#     "account",
#     'bootstrapform',
#     # 'selectize',
#     'paypal.standard.ipn',
#     'captcha',
#     # custom apps
    
#     'payments',    
#     'ajaxviews',
# )
# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     "account.middleware.LocaleMiddleware",
#     "account.middleware.TimezoneMiddleware",
#     # 'homepage.custom_middleware.RestrictAdminMiddleware',
# ]
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [
#             os.path.join(BASE_DIR, 'mysite','templates'),
#         ],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
# # MIDDLEWARE_CLASSES = (
# #     'django.contrib.sessions.middleware.SessionMiddleware',
# #     'django.middleware.common.CommonMiddleware',
# #     'django.middleware.csrf.CsrfViewMiddleware',
# #     'django.contrib.auth.middleware.AuthenticationMiddleware',
# #     'django.contrib.messages.middleware.MessageMiddleware',
# #     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# #     "account.middleware.LocaleMiddleware",
# #     "account.middleware.TimezoneMiddleware",
# #     'homepage.custom_middleware.RestrictAdminMiddleware',
# # )
# AUTH_USER_MODEL = 'ajaxviews.MyUser'
# ROOT_URLCONF = 'mysite.urls'

# WSGI_APPLICATION = 'mysite.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/1.6/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# # Internationalization
# # https://docs.djangoproject.com/en/1.6/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_L10N = True

# USE_TZ = False

# SITE_ID = 1
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/1.6/howto/static-files/

# on_webfaction=False
# if on_webfaction:
#     STATIC_URL = 'http://static.flexspot.webfactional.com/flexspot/'
#     MEDIA_URL = STATIC_URL+'media/'
#     STATIC_ROOT='/home/flexspot/webapps/htdocs/flexspot/'
#     MEDIA_ROOT = os.path.join(STATIC_ROOT,'media')
#     TIME_ZONE = 'US/Eastern'
#     DATABASES = {
# 	'default': {
# 		'ENGINE': 'django.db.backends.mysql', 
# 		'NAME': 'flexspotdb',
# 		'USER': 'flexspot_user',
# 		'PASSWORD': 'Flexspot123',
# 		'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
# 		'PORT': '3306',
# 	}
#     }
# else:
#     STATIC_URL = '/static/'
#     MEDIA_URL = '/static/media/'
#     MEDIA_ROOT = os.path.join(BASE_DIR,'homepage','static', 'media')

